name: Android Debug APK
on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 1) JDK 17 só para o Android SDK
      - name: Set up JDK 17 (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 2) Troca para JDK 11 para compilar (compatível com AGP antigo)
      - name: Set up JDK 11 (for build)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug -x lint --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            app/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/debug/*.apk
